# If desired, custom request types can be defined and choosen here
uint8 request_type

# Request message displayed to the operator
# Provide context information, i.e. for which purpose the data is required.
string msg

---

uint8 RESULT_OK 		= 0
uint8 RESULT_FAILED		= 1
uint8 RESULT_ABORTED	= 2

# Indicates if the request has been successful
uint8 result_code

# Serialized data which was requested
# In case of result_code != RESULT_OK, this field will contain unserialized data regarding the reason of failure instead.
string data

---
